### PR TITLE
Post requests

### PR DESCRIPTION
**Pull request by pezra**

### CODE REVIEW

**Comment by pezra** [comment]
ping

**Comment by passy** [comment]
Hey @pezra,

thank you for being so patient and sorry for being such a terrible maintainer. :/ There seems to be sufficient demand for handling `POST` and unsafe requests, but the core library is not the right place for this. Firstly, I think that having a free-form post operation encourages the use of out-of-band information which I think is against the spirit of HAL. Secondly, if we added those operations to `hyperagent` core, that would arguably open the box of pandora for more similar operations. And given my recent track record of time I can bring up for maintenance, I don't think that would be a great idea.

All that said, I think all of this should be possible as an addon in the spirit of [`hyperagent-forms`](https://github.com/weluse/hyperagent-forms) which should get you the best of both worlds. You can use the post operation natively on the Resource while we can keep the core library small. What are your thoughts on this?

**Comment by xogeny** [comment]
Just a comment...I'm interested in this functionality wherever it ends up.  So please provide updates on whatever is next.  I understand the need to keep the core clean, but I'm completely with @pezra that there are perfectly viable (and, in fact, very useful) ways to use HAL in conjunction with `POST`.

**Comment by pezra** [comment]
Fwiw, free form posts don't necessarily entail out of band knowledge. The
knowledge needed should be implicit in the media type and rel being used
and therefore in band.

I appreciate the desire to keep to the core library small. However, doing
so by excluding critical web API interaction patterns seems a suboptimal
way to accomplish that goal. Supporting the full range of http methods
wouldn't significantly increase the size of the core library. It would only
require the addition of 4 rather simple methods: post, patch, put and
delete. Of those put, delete and maybe patch seem uncontroversial under
your stated rubric since they require no special ahead of time knowledge of
the request body.

These methods are so vital to HTTP and to most nontrivial APIs that not
supporting them is a huge missed opportunity. Imo, adding these four small,
rather simple, methods would a huge win and well worth their quite minimal
cost.

**Comment by xogeny** [comment]
To put this in a little bit of perspective...imagine if you came across a web server where the maintainers said they only wanted to support `GET` and not `PUT`, `PATCH`, `POST` or `DELETE` in order to keep the core simple. :-)

**Comment by mattclarkdotnet** [comment]
Even the definitive HAL example API at http://haltalk.herokuapp.com/explorer/browser.html#/, which Hyperagent uses bits of in examples, requires a POST to sign up.

**Comment by passy** [comment]
I totally see your point that every non-trivial application is going to make use of Non-GET requests, but this library will remain scoped to what the official spec covers. And as @mattclarkdotnet mentions, even the definitive example uses POST, but clearly annotates it as out-of-band information that is not actually part of the HAL interface.

[HAL/Hyperagent Forms](https://github.com/weluse/hyperagent-forms) is one way to deal with this restriction, that I used myself, and I'd like to encourage you to take the same approach for the POST/PUT/DELETE implementation. I'm more than happy to add more affordances to the main library to make interfacing/extending it easier and if you think that adding an example of using those functions to the main docs while referencing the library, I'd also be happy to add this here.

What are your thoughts on this?

**Comment by mattclarkdotnet** [comment]
I think the distinction that needs to be made is between the document specification (which is what the HAL spec covers) and HAL client implementation.  hyperagent as a HAL **document** implementation shouldn't care about GETs or POSTs, but as a **client** implementation I think it should.

I've put up a very simple python HAL client at https://github.com/mattclarkdotnet/haleasy which shows what I personally like in a hypermedia client, but you can observe from the source that it actually knows almost nothing about HAL.  All the HAL document knowledge is in Will Harris' excellent dougrain library (https://github.com/wharris/dougrain)

**Comment by pezra** [comment]
To be blunt, I think it is ridiculous. I am unlikely to spend any effort patching functionality onto hyperagent with bailing wire and ductape that should, and could very easily, be built in. If your mind is set, though, I will leave stop wasting your and my time and find a solution that works better for me. Perhaps another library or a fork of this one.

**Comment by xogeny** [comment]
I'd just like to elaborate a bit on my perspective.  My interest in HAL is driven primarily by my interest in hypermedia.  Frankly, I think I've been spoiled for non-HATEOAS approaches now.  When I see an API where I have to "build" URLs, I just shiver.  The biggest issue I see in this space is how few people are really aware of the possibilities here.  It should be obvious to people the advantages of using hyperlinking given all the success of the browser.  But most people I know working on APIs still think of HATEOAS as some overly fancy approach.

Now let's consider this discussion framed by this issue.  I want APIs full of hyperlinks (URIs).  It seems strange to me that an API provides URIs but then dictates which HTTP verbs I'm allowed to use them with.  Especially since HAL, unlike Siren, doesn't explicitly specify actions (i.e. associations between URIs and verbs).

The point is that HAL may not formalize a way to marshal data for a `POST`.  **But who said that the URIs in my API all point to HAL endpoints?!?**  Are we saying that HAL APIs are not allowed to interoperate with the rest of the web and non-HAL endpoints?  Are we going to be that ideological?  If we want to bring the "wisdom" of HATEOAS to more people, we need to be pragmatic in my opinion.

Has anybody been paying attention to the most recent [JSON-API proposal](https://github.com/json-api/json-api/pull/341)?  It's a competing "hypermedia" approach that not only doesn't require URIs for resources but DOES require Ids.  When I asked them why they would offer up such a watered-down hypermedia format when HAL, Siren and Collection+JSON all require URIs for each resource, there response was "that's why nobody uses those formats".

One last thing to think about...we have a **long** way to go.  I've seen other client libraries (_e.g.,_ [traverson](https://github.com/basti1302/traverson)) that also have "follow" methods for following HAL links, _etc_.  But there is so much more we need to do.  For example, I submitted [a PR](https://github.com/jagregory/halgo/pull/6) for Golang client library to pick up the `Location` header from a `POST` that returns a `201` or a `202`.  My point is that we need to think about functionality well beyond just "follow" and we should help define what a reasonable set of pragmatic features should be.

To me, we are still in the nascent stages of this hypermedia renaissance.  What I'd like to see in future in developments (of something) is higher-level functionality built on top of a solid HATEOAS architectures.  Remember that the goal here is to be able to keep all the logic on the server side and build client code around hypermedia concepts (i.e., to avoid hardcoding of URLs, etc).  At least, that is my goal.  So for me, the question is how can we build richer hypermedia capabilities on top of the foundation that HAL lays down?  If `hyperagent` wants to just focus on that "foundation", I guess that is your right.  But to really get people to understand HATEOAS approaches, we need something, somewhere that builds on that foundation and provides a complete "vocabulary" for interacting with hypermedia APIs.

At least, that is how I see it.

**Comment by mattclarkdotnet** [comment]
Great post xogeny.  We have to remember that hypermedia is a layer on top of REST, so any HAL client must support a good subset of basic REST client functionality.  {'foo':'bar'} is a valid HAL document because it's a valid JSON document.

Having been responsible for teams implementing many HAL APIs over the past few years, and also clients connecting to them (mostly internal to an organisation I should say), it's clear to me that a big thing holding hypermedia APIs back is the lack of good quality client implementations.  Time and again teams need to reimplement, debug, struggle with and otherwise waste time on what should be a pretty basic capability.

Poor clients mean not only pain for users of hypermedia APIs in their own codebase, but also mean that writers of APIs are not held to any account for making usable APIs in the first place.

So as to the core topic, I think hyperagent is the nicest HAL client for JS I've seen, and it would be great if it could be built upon to create a 'good enough for most people most of the time' default HAL client for JS, so people could get on with making APIs that 'work with hyperagent' and therefore work with any other nice HAL clients.  It'll have to get POST functionality for that to happen though :-)

**Comment by passy** [comment]
@pezra I'm disappointed by that response. I don't see the point why adding functionality to the core that works perfectly well as a library. Especially, when there are applications that do not require it. But it's your choice. Feel free to fork the library instead, if you prefer going down that route. I feel like I must have done a terrible job explaining my position if it provoked a reaction like this. I definitely appreciate the contribution, I simply prefer keeping libraries small and extensible which by no means implies that I think this is wrong or unnecessary.

@xogeny Great post, indeed! I very much agree on your sentiment towards JSON-API, even though I think if this can be used as a way to getting more people interested into hypermedia APIs, it's definitely a good thing.

**Comment by mattclarkdotnet** [comment]
@passy the python HALEasy client I made recently (see post above) is less than 100 lines of code and supports GET, POST, PUT, and DELETE, as well as automatically following Location: headers using the correct HTTP method.  These are things any REST client has to do.

It makes perfect sense not to add in these things to a HAL document library, but in that case it shouldn't even support GET.   I urge you to reconsider how you are viewing the role of hyperagent.  There are people crying out for a full-featured HAL client for JS, and you could own that space very easily as is shown by the number of people on this thread.  Listen to your users!

**Comment by xogeny** [comment]
I agree with @mattclarkdotnet.  I now understand his distinction here between document libraries and client libraries.  In fact, this is very much the way traverson has gone because it leverages an external document library.

@passy I suppose you are concerned here about the "slippery slope" of having to support everything.  But I agree with @mattclarkdotnet that a client library should support all verbs.  As I said previously, my HAL API might point to non-HAL endpoints.  I should be able to interact with them.  Also, the fact that HAL doesn't really define a payload format for `POST`s doesn't mean you can't `POST`.  I have an API that is HAL compliant to the extent that HAL applies.  But in cases where HAL simply doesn't specify anything, I can't just stop there.  I still need the ability to `POST` and I provide my own implementation.

I guess I still don't fully understand your position here.  If `hyperagent` is a document library, I could understand it.  But as a client library, I think it needs to embrace all of HTTP, not just the parts that are explicitly related to HAL.

That being said, I completely respect your opinion to manage your project the way you want.  I'm not trying to bully or nag you in anyway.  I'm just trying to be constructive in giving you my perspective and reinforcing the comments of @mattclarkdotnet.  So I hope you take my comments in that spirit.

**Comment by mattclarkdotnet** [comment]
@xogeny Given that most HAL requests have an accept header of application/json, the return content type for a POST is perfectly well defined.  It's JSON.  That's why any well written HAL library will create a HAL document out of any arbitrary JSON, adding a _self link as it goes.

**Comment by passy** [comment]
One issue I have that hasn't been mentioned here before is that "all verbs" is more than just `GET`, `POST`, `PUT`, `PATCH` and `DELETE` since RFC-2616 doesn't limit it to these and there are real-world applications out there with custom methods. Which is why I feel like opening pandora's box by adding a subset of those to the library.

**Comment by xogeny** [comment]
@mattclarkdotnet You misunderstood me.  I was talking about the payload of the `POST` (the data you _upload_).  I agree with you about the response.

**Comment by xogeny** [comment]
@passy RFC-2616 does define a set of "common verbs".  I'm talking about supporting those.  In fact, RFC-2616 explicitly says:

> Although this set can be expanded, additional methods cannot be assumed to share the same semantics for separately extended clients and servers.

So I think that lets us off the hook with regards to non-common verbs.  I don't think there is any Pandora's box here because you could not reasonably anticipate the semantics of such custom verbs.

**Comment by mattclarkdotnet** [comment]
@xogeny ah I see, but the same argument applies - the payload content is what you set the content-type header to.  If a rel such as 'upload-video' needs specific content types to be sent to it, then it should be documented as a type property, and ideally also a profile property of the rel.  Otherwise assume application/json.  To be honest I'd rather 'methods' and 'type' were mandatory properties of HAL links as it would save a lot of online debate...

**Comment by mattclarkdotnet** [comment]
@passy in the real world GET, POST, PUT and DELETE are all you need.  There is no pandora's box unless you hang out in a theory-only echo chamber.  I need exactly zero fingers to count the number of times someone complained about a real API because it didn't support PATCH.  In fact hypermedia makes PATCH nearly obsolete because you can use meaningful rels instead of an HTTP verb which is often misunderstood and in practice downright confusing.

**Comment by xogeny** [comment]
@mattclarkdotnet Again, I think we are in violent agreement. :-)

I was simply responding the @passy's comment about `POST` payloads as being "out of band" and "not actually part of the HAL interface".

**Comment by mattclarkdotnet** [comment]
@xogeny no argument implied :-)

**Comment by pezra** [comment]
@passy, i appreciate the response.

> I don't see the point why adding functionality to the core that works perfectly well as a library. 

Of course this functionality could be implemented separately. However, the full suite of HTTP methods are, in my view, such an important part of hypermedia web APIs that any client that make it hard to use any of them is, in a very fundamental and systemic way, broken. 

> Feel free to fork the library instead, if you prefer going down that route.

I really, really don't want to do that. Hence my repeated futile attempts to sway your thinking. :)

> I feel like I must have done a terrible job explaining my position

I feel the same way. I am not trying to be a jerk, but i do care a great deal about the tools i use. My reaction is due much more to my disappointment than to your explanation. The fact remains, though, that if hyperagent is currently as good (and i do view it as quite a good start) as it is ever going to get then i think i'd rather invest my time in a tool with a bit more potential.

**Comment by pezra** [comment]
@passy, i'm closing this to get it off my dashboard. If you change your mind feel free to reopen it.

**Pull request closed without merging**
